version: "3"
services:
  frontend:
    build:
      context: ./frontend/vite-project
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/skill_recommendation
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
